spring:
  application:
    name: gorae

  datasource:
    url: jdbc:mariadb://localhost:3306/gorae?serverTimezone=UTC&characterEncoding=utf8
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
